/*
	Outdated
*/

CREATE TABLE data (
	`ID` INT PRIMARY KEY,
	`lat` DOUBLE,
	`lon` DOUBLE,
	`locationName` VARCHAR(64),
	`stationId` VARCHAR(64),
	`obsTime` TIMESTAMP,
	`ELEV` FLOAT,
	`RAIN` FLOAT,
	`MIN_10` FLOAT,
	`HOUR_3` FLOAT,
	`HOUR_6` FLOAT,
	`HOUR_12` FLOAT,
	`HOUR_24` FLOAT,
	`NOW` FLOAT,
	`latest_2days` FLOAT,
	`latest_3days` FLOAT,
	`HOUR_3` FLOAT,
	`CITY` VARCHAR(16),
	`CITY_SN` VARCHAR(16),
	`TOWN` VARCHAR(16),
	'TOWN_SN' VARCHAR(16),
	`ATTRIBUTE` VARCHAR(16)
)